import SmoothScroll from "@components/SmoothScroll";
import "./globals.css";
import Navbar from "@components/Navbar";
import Footer from "@components/Footer";
import GoToTopButton from "@components/GoToTop";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll>
          <Navbar />
          <GoToTopButton />
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
